version: 2

project_name: gitlab-ci-visualizer

before:
  hooks:
  - go mod tidy

builds:
- id: glvis
  main: .
  binary: glvis
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  ldflags:
  - -s -w

archives:
- id: default
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    formats:
    - zip
  files:
  - README.md
  - LICENSE

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yyewolf
    name: gitlab-ci-visualizer
  name_template: "v{{ .Version }}"
