when:
  event: [ push, pull_request ]

steps:
- name: web-build
  image: node:22-alpine
  commands:
  - npm --prefix web ci
  - npm --prefix web run build

- name: go-test
  image: golang:latest
  commands:
  - go test ./...

- name: go-lint
  image: golangci/golangci-lint:latest
  commands:
  - golangci-lint run ./...

- name: vscode-typecheck
  image: node:22-alpine
  commands:
  - npm --prefix vscode ci
  - cd vscode && ./node_modules/.bin/tsc --noEmit
